services:

  orchestrator:
    build:
      context: .
      dockerfile: orchestrator.dockerfile
    ports:
      - "8080:8080"
    environment:
      "TIME_ADDITION_MS": "200"
      "TIME_SUBTRACTION_MS": "200"
      "TIME_MULTIPLICATIONS_MS": "300"
      "TIME_DIVISIONS_MS": "400"

  agent:
    build:
      context: .
      dockerfile: agent.dockerfile
    depends_on:
      - orchestrator
    environment:
      "COMPUTING_POWER": "4"
      "ORCHESTRATOR_URL": "http://orchestrator:8080"

